---
title: 'Master en Big Data. Fundamentos  matemáticos  del  análisis  de  datos.' 
author: "Fernando San Segundo"
date: 'Curso 2019-20. Última actualización: `r format(Sys.time(), "%Y-%m-%d")`'
subtitle: "Preguntas sobre R tipo examen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1. 

1. Carga el set [AustinCityLimits](https://raw.githubusercontent.com/fernandosansegundo/MBDFME/master/datos/AustinCityLimits) y haz un análisis exploratorio inicial:
    - ¿Cuántos artistas hay en el dataset?
    - ¿Cuántos de los 10 primeros artistas ganaron un Grammy?
    - ¿Qué género toca la primera mujer del dataset de más de 60 años?

2. Crea una tabla de probabilidad marginal del género y sexo

3. Selecciona los artistas mayores de 30 años y muestra la tabla de contingencia para el sexo y
el género de música

4. Calcula la probabilidad de que se toque cada uno de los géneros. Ahora calcula esta misma probabilidad sabiendo el sexo del artista: ¿Cuál es la probabilidad de que una artista femenina toque rock/folk/indie? ¿Cuál es la probabilidad de que un artista masculino toque rock/folk/indie?

5. Con los datos anteriores calcula la proporción de cantantes de jazz que eran hombres y la proporción de hombres que cantaban jazz.

6. ¿Existe alguna relación entre el estilo de música que toca un artista masculino y ganar un Grammy?
    - Selecciona sólo los artistas masculinos
    - Crea una tabla que muestre las distribuciones marginales para el estilo y los Grammy
    - Crear una tabla de contingencia para mostrar las distribuciones condicionadas para el estilo y los Grammy
    - Haz un diagrama de barras para visualizar cuántos artistas de cada estilo obtuvieron un Grammy.
    - Calcula la probabilidad de ganar un Grammy
    - Calcula la probabilidad de ganar un Grammy en función del estilo.
    - Interpreta la relación entre el género que se toca y ganar un Grammy

## Ejercicio 2.

El set de datos [FilmData.csv](https://raw.githubusercontent.com/fernandosansegundo/MBDFME/master/datos/FilmData.csv)  recoge datos de las películas más taquilleras del cine:
  
1. ¿Existe alguna relación entre el género de la película y el estudio? ¿Existe alguna relación entre el número de días que permanece una película en el cine y el estudio? Justifica la respuesta al menos gráficamente. 

2. ¿Existe relación entre el presupuesto de una película y su recaudación? ¿Y entre la recaudación y la nota obtenida en Rotten Tomatoes?

3. ¿Es coherente la evaluación de Rotten y IMDB? ¿Cuál es la película en la que hubo más desacuerdo entre las dos críticas?
  
4. Crea un modelo de regresión para poder predecir la valoración de la crítica en Rotten o en IMDB (se supone que no se dispone de ninguna de las dos). Contempla la idea de hacer segmentación.

## Ejercicio 3.

Carga los datos de [airbnb.csv](https://raw.githubusercontent.com/fernandosansegundo/MBDFME/master/datos/airbnb.csv) en Madrid compilados en septiembre de 2017.

1. Analiza el set de datos:
    + Tipo de variables
    + Si hay datos incompletos
    + Variables categóricas: (selecciona las dos que consideres más significativas) conteo,
    moda, gráfico
    + Variables continuas: (selecciona las tres que consideres más significativas) estadísticos
    básicos, gráficos

2. Analiza la información que nos dan estos datos:
    + El anfitrión que más viviendas tiene, ¿cuántas tiene?¿Son viviendas que tiene destinadas
    al alquiler? Se considera que están destinadas al alquiler cuando están disponible más
    de la mitad del año para este fin.
    + ¿Qué barrio (neighbourhood_group) tiene mayor proporción de casas alquiladas,
    habitaciones privadas y habitaciones compartidas?
    + ¿Es rentable alquilar una habitación compartida en lugar de una privada? Suponemos
    que es rentable cuando sale por al menos la mitad de precio. Analiza esta cuestión por
    barrios.
    + ¿Cuál es el máximo del número de noches mínimo que se pide para alquilar una
    habitación compartida?

3. Relación entre variables
    + En los pisos que se alquila una habitación privada ¿Existe dependencia entre el barrio y
    el precio?
    + Suponiendo que todos los que alquilan escriben una review, ¿existe alguna relación
    entre el precio y las reviews totales?
    + ¿Existe relación entre el barrio y el tipo de alquiler que se ofrece?

<!-- 4. En el set de datos idealista tenemos los precios medios de alquiler mensual por metro cuadrado. Analiza: -->
<!--     + Suponiendo que estos precios se mantienen en alquileres de pisos enteros en airbnb que se alquilan durante más de 6 meses, ¿cuál sería el tamaño medio de los pisos por barrio?¿Tiene sentido? ¿Qué conclusión podemos sacar? -->
<!--     + Viendo la evolución de los precios por metro cuadrado, ¿en qué barrio se alquilaría una vivienda si lo quiere es vivir en la zona con precio más estable? -->
