---
title: 'Master en Big Data. Fundamentos  matemáticos  del  análisis  de  datos.' 
author: "Fernando San Segundo"
date: 'Curso 2019-20. Última actualización: `r format(Sys.time(), "%Y-%m-%d")`'
subtitle: "Tema 7: Modelos. Representación 3d del plano de regresión para childData"
output: html_document
---

```{r setup, include=FALSE, results='hide'}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(rgl)
setupKnitr()
knit_hooks$set(webgl = hook_webgl)
```

+ Puedes girar y hacer zoom en la figura con el ratón.
+ El código que produce la figura se puede ver aquí (sólo si estás muy interesado).

```{r echo=FALSE, webgl=TRUE, results='hide'}
childData = data.frame(
  wgt = c(64, 71, 53, 67, 55, 58, 77, 57, 56, 51, 76, 68), 
  hgt = c(57, 59, 49, 62, 51, 50, 55, 48, 42, 42, 61, 57), 
  age = c(8, 10, 6, 11, 8, 7, 10, 9, 10, 6, 12, 9))
data = childData
namesData = colnames(data) 
colnames(data) = c("x1", "x2", "y")
open3d()
plot3d(data$x1, data$x2, data$y, col="blue", size=8, 
       xlab="", ylab="", zlab="")
lm2 = lm(y ~ x1 + x2, data)
points3d(data$x1, data$x2, lm2$fitted.values, col="cyan", size=8)
segments3d(x=rep(data$x1, rep(2, length(data$x1))), y=rep(data$x2, rep(2, length(data$x2))), z=c(t(cbind(data$y, lm2$fitted.values))), col="red", lwd=2)


Plane <- function(x1, x2) {
  beta  = lm2$coefficients 
  beta[1] + beta[2] * x1 + beta[3] * x2
}

minx = min(data$x1)
maxx = max(data$x1)
miny = min(data$x2)
maxy = max(data$x2)

nx = 20
ny = 100

x= seq(minx, maxx, length.out = nx)
y= seq(miny, maxy, length.out = ny)

xnet = rep(x, ny)
ynet = rep(y, rep(nx,ny))


XY = matrix(c(xnet, ynet), ncol = 2)

znet = apply(XY, MARGIN = 1, FUN = function(x)(Plane(x1 = x[1], x2 = x[2])))

points3d(xnet, ynet, znet, col="darkgreen")

nx = 100
ny = 20

x= seq(minx, maxx, length.out = nx)
y= seq(miny, maxy, length.out = ny)


ynet = rep(y, nx)
xnet = rep(x, rep(ny,nx))
XY = matrix(c(xnet, ynet), ncol = 2)
znet = apply(XY, MARGIN = 1, FUN = function(x)(Plane(x1 = x[1], x2 = x[2])))
points3d(xnet, ynet, znet, col="darkgreen")
colnames(data) = namesData 
```

